package spdvid.evtmallorca.dialogs;

import spdvid.evtmallorca.dataaccess.DataAccess;
import spdvid.garciajodar_tarea1.dto.Usuari;

/**
 *
 * @author Miguel
 */
public class UserDataDialog extends javax.swing.JDialog {

    DataAccess da;
    Usuari user;
    
    
    /**
     * Creates new form LoginDialog
     */
    public UserDataDialog(java.awt.Frame parent, boolean modal, Usuari user) {
        super(parent, modal);
        this.user = user;
        initComponents();
        llenarDatos();
        setLocationRelativeTo(null);
        setSize(new java.awt.Dimension(400, 370));
        da = new DataAccess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLlinatges = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblNom = new javax.swing.JLabel();
        lblLlinatges = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtEmail2 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        txtLlinatges.setText("eforbearb@ucsd.edu");
        getContentPane().add(txtLlinatges);
        txtLlinatges.setBounds(200, 130, 180, 22);

        btnUpdate.setText("Actualitzar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(100, 270, 180, 23);

        lblNom.setText("Nom");
        getContentPane().add(lblNom);
        lblNom.setBounds(10, 100, 180, 16);

        lblLlinatges.setText("Llinatges");
        getContentPane().add(lblLlinatges);
        lblLlinatges.setBounds(200, 100, 180, 16);
        getContentPane().add(separator);
        separator.setBounds(0, 80, 410, 20);

        lblTitle.setFont(lblTitle.getFont().deriveFont(lblTitle.getFont().getStyle() | java.awt.Font.BOLD, 18));
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-editar-usuario-masculino-48.png"))); // NOI18N
        lblTitle.setText("Panell de Control Usuari");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(0, 0, 390, 70);

        txtNom.setText("eforbearb@ucsd.edu");
        getContentPane().add(txtNom);
        txtNom.setBounds(10, 130, 170, 22);

        txtEmail2.setText("eforbearb@ucsd.edu");
        getContentPane().add(txtEmail2);
        txtEmail2.setBounds(10, 210, 170, 22);

        txtEmail.setText("Email");
        getContentPane().add(txtEmail);
        txtEmail.setBounds(10, 180, 180, 16);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(200, 210, 180, 22);

        lblPassword.setText("Contrasenya");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(200, 180, 180, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        user.setNom(txtNom.getText());
        user.setLlinatges(txtLlinatges.getText());
        user.setEmail(txtEmail.getText());
        user.setPassword(txtPassword.getText());
        
        
        da.updateUser(user);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void llenarDatos(){
        txtNom.setText(user.getNom());
        txtLlinatges.setText(user.getLlinatges());
        txtEmail.setText(user.getEmail());
      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblLlinatges;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtLlinatges;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
