package spdvid.evtmallorca;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.ui.FlatCheckBoxUI;
import java.awt.Font;
import javax.swing.JCheckBox;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import spdvid.evtmallorca.dialogs.LoginDialog;
import spdvid.evtmallorca.dto.Allotjament;
import spdvid.evtmallorca.panels.PanelDetallAllotjament;
import spdvid.evtmallorca.panels.PanelInsertAllotjament;
import spdvid.evtmallorca.panels.PanelLlistaAllojtaments;
import spdvid.garciajodar_tarea1.dto.Usuari;

/**
 *
 * @author Miguel
 */
public class Main extends javax.swing.JFrame {

    private Usuari authenticatedUser = null;
    private PanelLlistaAllojtaments pnlAllojtaments = null;
    private PanelDetallAllotjament pnlDetallAllotjament = null;
    private PanelInsertAllotjament pnlInsertAllotjament = null;

    /**
     * Creates new form Main
     */
    public Main() {
        FlatDarculaLaf.setup();
        try {
            UIManager.setLookAndFeel(new FlatDarculaLaf());
            Font font = new Font("Roboto", Font.PLAIN, 12);
            UIManager.put("Label.font", font);
            UIManager.put("Button.font", font);
            UIManager.put("TextField.font", font);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println(e);
        }
        initComponents();
        pack();
        btnLogout.setVisible(false);
        btnUserData.setVisible(false);
        pnlMain.setVisible(false);
        lblWelcomeMessage.setText("No hi ha ningu connectat.");
        lblWelcomeMessage.setVisible(true);
        this.setSize(550, 200);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnShowLoginDialog = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcomeMessage = new javax.swing.JLabel();
        btnUserData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.setMinimumSize(new java.awt.Dimension(780, 700));
        pnlMain.setPreferredSize(new java.awt.Dimension(780, 700));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        lblTitle.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-hotel-60.png"))); // NOI18N
        lblTitle.setText("EVT MALLORCA");
        lblTitle.setIconTextGap(10);

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnShowLoginDialog.setForeground(new java.awt.Color(255, 255, 255));
        btnShowLoginDialog.setText("Login");
        btnShowLoginDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLoginDialogActionPerformed(evt);
            }
        });

        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Sign out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblWelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWelcomeMessage.setText("Welcome username");
        lblWelcomeMessage.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnUserData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-encuentra-hombre-usuario-48.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowLoginDialog)
                    .addComponent(btnLogout)
                    .addComponent(lblWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUserData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUserData, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWelcomeMessage)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnShowLoginDialog))
                                .addGap(18, 18, 18)
                                .addComponent(btnLogout)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnShowLoginDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLoginDialogActionPerformed
        LoginDialog loginDialog = new LoginDialog(this, true);
        loginDialog.setVisible(true);
        if (authenticatedUser != null) {
            btnShowLoginDialog.setVisible(false);
            btnLogout.setVisible(true);
            btnLogout.setEnabled(true);
            btnUserData.setVisible(true);
            btnUserData.setEnabled(true);
            lblWelcomeMessage.setText("Benvingut " + authenticatedUser.getNom());
            lblWelcomeMessage.setVisible(true);
            pnlAllojtaments = new PanelLlistaAllojtaments(authenticatedUser.getId(), this);
            pnlMain.removeAll();
            pnlMain.add(pnlAllojtaments);
            pnlMain.repaint();
        }
    }//GEN-LAST:event_btnShowLoginDialogActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        authenticatedUser = null;
        btnShowLoginDialog.setVisible(true);
        btnLogout.setVisible(false);
        btnUserData.setVisible(false);
        lblWelcomeMessage.setText("No hi ha ningu connectat.");
        pnlMain.removeAll();
        pnlMain.repaint();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        btnLogout.setEnabled(false);
        //btnLogout.setVisible(false);
        lblWelcomeMessage.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    public void userLoggedIn(Usuari user) {
        authenticatedUser = user;
    }

    public void showPnlDetallAllotjament(Allotjament allotjament) {
        pnlDetallAllotjament = new PanelDetallAllotjament(allotjament, this);
        pnlMain.removeAll();
        pnlMain.add(pnlDetallAllotjament);
        pnlMain.repaint();
        pnlMain.setSize(400, 700);
        this.setSize(900, 800);
    }

    public void showPnlLlistaAllotjaments() {
        pnlMain.removeAll();
        pnlMain.add(pnlAllojtaments);
        pnlMain.repaint();
        pnlMain.setSize(400, 700);
        this.setSize(600, 700);
    }

    public void showPnlInsertAllotjament() {
        pnlMain.removeAll();
        pnlInsertAllotjament = new PanelInsertAllotjament(this);
        pnlMain.add(pnlInsertAllotjament);
        pnlMain.repaint();
        pnlMain.setSize(400, 700);
        this.setSize(600, 700);

    }

    public Usuari getAuthenticatedUser() {
        return authenticatedUser;
    }

    public void reloadPnlLlistaAllotjaments() {
        pnlMain.removeAll();
        pnlAllojtaments = new PanelLlistaAllojtaments(authenticatedUser.getId(), this);
        pnlMain.add(pnlAllojtaments);
        pnlMain.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnShowLoginDialog;
    private javax.swing.JButton btnUserData;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
