package spdvid.evtmallorca;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import spdvid.evtmallorca.dialogs.LoginDialog;
import spdvid.evtmallorca.dialogs.UserDataDialog;
import spdvid.evtmallorca.dto.Allotjament;
import spdvid.evtmallorca.panels.PanelDetallAllotjament;
import spdvid.evtmallorca.panels.PanelInsertAllotjament;
import spdvid.evtmallorca.panels.PanelLlistaAllotjaments;
import spdvid.garciajodar_tarea1.dto.Usuari;

/**
 *
 * @author Miguel
 */
public class Main extends javax.swing.JFrame {

    private Usuari authenticatedUser = null;
    private PanelLlistaAllotjaments pnlAllotjaments = null;
    private PanelDetallAllotjament pnlDetallAllotjament = null;
    private PanelInsertAllotjament pnlInsertAllotjament = null;

    /**
     * Creates new form Main
     */
    public Main() {
        FlatDarculaLaf.setup();
        try {
            UIManager.setLookAndFeel(new FlatDarculaLaf());
            Font font = new Font("Roboto", Font.PLAIN, 12);
            UIManager.put("Label.font", font);
            UIManager.put("Button.font", font);
            UIManager.put("TextField.font", font);
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println(e);
        }
        initComponents();
        lblWelcomeMessage.setForeground(Color.red);
        btnLogout.setEnabled(false);
        btnUserData.setEnabled(false);
        this.setSize(640, 500);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jSeparatorVertical = new javax.swing.JSeparator();
        btnShowLoginDialog = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcomeMessage = new javax.swing.JLabel();
        btnUserData = new javax.swing.JButton();
        jSeparatorHorizontal = new javax.swing.JSeparator();
        pnlMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlTitle.setForeground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-hotel-60.png"))); // NOI18N
        lblTitle.setText("EVT MALLORCA");
        lblTitle.setIconTextGap(10);

        jSeparatorVertical.setForeground(new java.awt.Color(255, 255, 255));
        jSeparatorVertical.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnShowLoginDialog.setFont(btnShowLoginDialog.getFont().deriveFont(btnShowLoginDialog.getFont().getStyle() | java.awt.Font.BOLD));
        btnShowLoginDialog.setForeground(new java.awt.Color(255, 255, 255));
        btnShowLoginDialog.setText("Login");
        btnShowLoginDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowLoginDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLoginDialogActionPerformed(evt);
            }
        });

        btnLogout.setFont(btnLogout.getFont().deriveFont(btnLogout.getFont().getStyle() | java.awt.Font.BOLD));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Sign out");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblWelcomeMessage.setFont(lblWelcomeMessage.getFont().deriveFont(lblWelcomeMessage.getFont().getStyle() | java.awt.Font.BOLD));
        lblWelcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("Sin conexion");
        lblWelcomeMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnUserData.setForeground(new java.awt.Color(255, 255, 255));
        btnUserData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-encuentra-hombre-usuario-48.png"))); // NOI18N
        btnUserData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDataActionPerformed(evt);
            }
        });

        jSeparatorHorizontal.setForeground(new java.awt.Color(255, 255, 255));
        jSeparatorHorizontal.setMinimumSize(new java.awt.Dimension(900, 0));

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addComponent(jSeparatorHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(btnShowLoginDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(btnUserData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTitleLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jSeparatorVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(567, Short.MAX_VALUE)))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblWelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowLoginDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(btnUserData, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparatorHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
            .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTitleLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(9, Short.MAX_VALUE))
                .addGroup(pnlTitleLayout.createSequentialGroup()
                    .addComponent(jSeparatorVertical, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlMain.setMinimumSize(new java.awt.Dimension(780, 700));
        pnlMain.setPreferredSize(new java.awt.Dimension(640, 700));

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnShowLoginDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLoginDialogActionPerformed
        LoginDialog loginDialog = new LoginDialog(this, true);
        loginDialog.setVisible(true);
        loginDialog.setLocationRelativeTo(null);
        if (authenticatedUser != null) {
            btnShowLoginDialog.setEnabled(false);
            btnLogout.setVisible(true);
            btnLogout.setEnabled(true);
            btnUserData.setVisible(true);
            btnUserData.setEnabled(true);
            lblWelcomeMessage.setText("Benvingut " + authenticatedUser.getNom());
            lblWelcomeMessage.setForeground(Color.GREEN);
            lblWelcomeMessage.setVisible(true);
            pnlAllotjaments = new PanelLlistaAllotjaments(authenticatedUser.getId(), this);
            pnlMain.removeAll();
            pnlMain.add(pnlAllotjaments);
            pnlMain.repaint();
            this.setSize(640, 700);
        }
    }//GEN-LAST:event_btnShowLoginDialogActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        authenticatedUser = null;
        btnShowLoginDialog.setEnabled(true);
        btnLogout.setEnabled(false);
        btnUserData.setEnabled(false);
        lblWelcomeMessage.setText("Sin Conexion");
        pnlMain.removeAll();
        pnlMain.repaint();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        btnLogout.setEnabled(false);
        //btnLogout.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void btnUserDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDataActionPerformed
        // TODO add your handling code here:
        UserDataDialog userDialog = new UserDataDialog(this, true, authenticatedUser);
        userDialog.setVisible(true);
        userDialog.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnUserDataActionPerformed

    public void userLoggedIn(Usuari user) {
        authenticatedUser = user;
    }

    public void showPnlDetallAllotjament(Allotjament allotjament) {
        pnlDetallAllotjament = new PanelDetallAllotjament(allotjament, this, authenticatedUser);
        pnlMain.removeAll();
        pnlMain.add(pnlDetallAllotjament);
        pnlMain.repaint();
        pnlMain.setSize(640, 700);
        this.setSize(640, 850);
    }

    public void showPnlLlistaAllotjaments() {
        pnlMain.removeAll();
        pnlMain.add(pnlAllotjaments);
        pnlMain.repaint();
        this.setSize(640, 700);
    }

    public void showPnlInsertAllotjament() {
        pnlMain.removeAll();
        pnlInsertAllotjament = new PanelInsertAllotjament(this);
        pnlMain.add(pnlInsertAllotjament);
        pnlMain.repaint();
        this.setSize(640, 680);

    }

    public Usuari getAuthenticatedUser() {
        return authenticatedUser;
    }

    public void reloadPnlLlistaAllotjaments() {
        pnlAllotjaments = new PanelLlistaAllotjaments(authenticatedUser.getId(), this);
        showPnlLlistaAllotjaments();
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnShowLoginDialog;
    private javax.swing.JButton btnUserData;
    private javax.swing.JSeparator jSeparatorHorizontal;
    private javax.swing.JSeparator jSeparatorVertical;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTitle;
    // End of variables declaration//GEN-END:variables
}
