package spdvid.evtmallorca.panels;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import spdvid.evtmallorca.Main;
import spdvid.evtmallorca.dataaccess.DataAccess;
import spdvid.evtmallorca.dto.Allotjament;
import spdvid.evtmallorca.dto.Municipi;
import spdvid.evtmallorca.dto.Servei;

/**
 *
 * @author Miguel
 */
public class PanelInsertAllotjament extends javax.swing.JPanel {

    private Allotjament allotjament = null;
    private DataAccess da = new DataAccess();
    private Main mainJFrame = null;

    /**
     * Creates new form PanelDetallAllotjament
     */
    public PanelInsertAllotjament(Main mainJPanel) {
        initComponents();
        this.mainJFrame = mainJPanel;
        setSize(780, 490);

        inicialitzaFields();
    }

    private void inicialitzaFields() {
//        txtNom.setText(allotjament.getNom());
//        txtAdresa.setText(allotjament.getAdresa());
//        txaDescripcio.setText(allotjament.getDescripcio());
        initCmbMunicipis();
//        spnNumPersones.setValue(allotjament.getNum_persones());
//        txtPreuNit.setText(Float.toString(allotjament.getPreu_per_nit()));
//        initServeis();
    }

    private void initCmbMunicipis() {
        var municipis = da.getMunicipis();
        DefaultComboBoxModel<String> cbm = new DefaultComboBoxModel<>();
        for (Municipi m : municipis) {
            cbm.addElement(m.getNom());
        }
        cmbMunicipi.setModel(cbm);
//        cmbMunicipi.setSelectedItem(allotjament.getMunicipi());
    }

    private void initServeis() {
//        var serveis = da.getServeisAllotjament(allotjament.getId());
//        for (Servei s : serveis) {
//            switch(s.getDescripcio()) {
//                case "Piscina": chkPiscina.setSelected(true);
//                break;
//                case "Aire acondicionat": chkAireAcondicionat.setSelected(true);
//                break;
//                case "Wifi": chkWifi.setSelected(true);
//                break;
//                case "Aparcament": chkAparcament.setSelected(true);
//                break;
//                case "Admet mascotes": chkMascotes.setSelected(true);
//                break;
//                case "Ascensor": chkAscensor.setSelected(true);
//                break;
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jLabelnom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtAdressa = new javax.swing.JTextField();
        jLabelAdressa = new javax.swing.JLabel();
        txtDescripcio = new javax.swing.JTextField();
        jLabelDescripcio = new javax.swing.JLabel();
        jLabelMunicipi = new javax.swing.JLabel();
        txtValoracio = new javax.swing.JTextField();
        jLabelValoracio = new javax.swing.JLabel();
        jLabelPreu = new javax.swing.JLabel();
        jLabelNumPers = new javax.swing.JLabel();
        jSpinnerNomPers = new javax.swing.JSpinner();
        jSpinnerPreu = new javax.swing.JSpinner();
        cmbMunicipi = new javax.swing.JComboBox<>();
        pnlServeis = new javax.swing.JPanel();
        chkPiscina = new javax.swing.JCheckBox();
        chkMascotes = new javax.swing.JCheckBox();
        chkAscensor = new javax.swing.JCheckBox();
        chkAireAcondicionat = new javax.swing.JCheckBox();
        chkAparcament = new javax.swing.JCheckBox();
        chkWifi = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(780, 490));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Imatges"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 420, -1));

        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        btnInsert.setText("Insertar");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 80, 40));

        jLabelnom.setText("Nom:");
        add(jLabelnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtNom.setText("jTextField1");
        add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 137, -1));

        txtAdressa.setText("jTextField1");
        add(txtAdressa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 137, -1));

        jLabelAdressa.setText("Adressa:");
        add(jLabelAdressa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        txtDescripcio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDescripcio.setText("jTextField1");
        add(txtDescripcio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 420, 82));

        jLabelDescripcio.setText("Descripcio: ");
        add(jLabelDescripcio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabelMunicipi.setText("Municipi: ");
        add(jLabelMunicipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtValoracio.setText("jTextField1");
        add(txtValoracio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabelValoracio.setText("Valoració:");
        add(jLabelValoracio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabelPreu.setText("Preu:");
        add(jLabelPreu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabelNumPers.setText("Nº de Personas:");
        add(jLabelNumPers, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));
        add(jSpinnerNomPers, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 84, -1));
        add(jSpinnerPreu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        cmbMunicipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alaró", "Inca" }));
        add(cmbMunicipi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 137, -1));

        pnlServeis.setBorder(javax.swing.BorderFactory.createTitledBorder("Serveis"));

        chkPiscina.setText("Piscina");

        chkMascotes.setText("Mascotes");
        chkMascotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMascotesActionPerformed(evt);
            }
        });

        chkAscensor.setText("Ascensor");

        chkAireAcondicionat.setText("Aire Acondicionat");

        chkAparcament.setText("Aparcament");

        chkWifi.setText("Wifi");

        javax.swing.GroupLayout pnlServeisLayout = new javax.swing.GroupLayout(pnlServeis);
        pnlServeis.setLayout(pnlServeisLayout);
        pnlServeisLayout.setHorizontalGroup(
            pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServeisLayout.createSequentialGroup()
                .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServeisLayout.createSequentialGroup()
                        .addComponent(chkPiscina)
                        .addGap(32, 32, 32)
                        .addComponent(chkAireAcondicionat))
                    .addGroup(pnlServeisLayout.createSequentialGroup()
                        .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAscensor)
                            .addComponent(chkMascotes))
                        .addGap(18, 18, 18)
                        .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAparcament)
                            .addComponent(chkWifi))))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        pnlServeisLayout.setVerticalGroup(
            pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServeisLayout.createSequentialGroup()
                .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPiscina)
                    .addComponent(chkAireAcondicionat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAparcament)
                    .addComponent(chkMascotes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkWifi)
                    .addComponent(chkAscensor))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        add(pnlServeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 270, 110));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 20));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-hotel-bed-48.png"))); // NOI18N
        jLabel1.setText(" Nou Allotjament");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainJFrame.showPnlLlistaAllotjaments();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        allotjament = new Allotjament();
        allotjament.setNom(txtNom.getText());
        allotjament.setAdresa(txtAdresa.getText());
        allotjament.setMunicipi(cmbMunicipi.getSelectedItem().toString());
        allotjament.setId_municipi(cmbMunicipi.getSelectedIndex()+1);
        allotjament.setDescripcio(txaDescripcio.getText());
        try {
            spnNumPersones.commitEdit();
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }
        allotjament.setNum_persones((Integer) spnNumPersones.getValue());
        allotjament.setId_propietari(mainJFrame.getAuthenticatedUser().getId());
        float preuPerNit = Float.parseFloat(txtPreuNit.getText());
        allotjament.setPreu_per_nit(preuPerNit);
        int idNouAllotjament = da.insertAllotjament(allotjament);
        
        if (idNouAllotjament <= 0) {
            JOptionPane.showMessageDialog(mainJFrame, "Error inserting new allotjament.");
            return;
        }
        
        if (chkPiscina.isSelected()) {
            da.insertServei(1, idNouAllotjament);
        }
        if (chkMascotes.isSelected()) {
            da.insertServei(2, idNouAllotjament);
        }
        if (chkAireAcondicionat.isSelected()) {
            da.insertServei(3, idNouAllotjament);
        }
        if (chkAscensor.isSelected()) {
            da.insertServei(4, idNouAllotjament);
        }
        if (chkAparcament.isSelected()) {
            da.insertServei(5, idNouAllotjament);
        }
        if (chkWifi.isSelected()) {
            da.insertServei(6, idNouAllotjament);
        }
        
        JOptionPane.showMessageDialog(mainJFrame, "Allotjament inserted correctly.");
        
        mainJFrame.reloadPnlLlistaAllotjaments();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void chkMascotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMascotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMascotesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInsert;
    private javax.swing.JCheckBox chkAireAcondicionat;
    private javax.swing.JCheckBox chkAparcament;
    private javax.swing.JCheckBox chkAscensor;
    private javax.swing.JCheckBox chkMascotes;
    private javax.swing.JCheckBox chkPiscina;
    private javax.swing.JCheckBox chkWifi;
    private javax.swing.JComboBox<String> cmbMunicipi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdressa;
    private javax.swing.JLabel jLabelDescripcio;
    private javax.swing.JLabel jLabelMunicipi;
    private javax.swing.JLabel jLabelNumPers;
    private javax.swing.JLabel jLabelPreu;
    private javax.swing.JLabel jLabelValoracio;
    private javax.swing.JLabel jLabelnom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerNomPers;
    private javax.swing.JSpinner jSpinnerPreu;
    private javax.swing.JPanel pnlServeis;
    private javax.swing.JTextField txtAdressa;
    private javax.swing.JTextField txtDescripcio;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtValoracio;
    // End of variables declaration//GEN-END:variables
}
