package spdvid.evtmallorca.panels;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import spdvid.evtmallorca.Main;
import spdvid.evtmallorca.dataaccess.DataAccess;
import spdvid.evtmallorca.dto.Allotjament;
import spdvid.evtmallorca.dto.Municipi;
import spdvid.evtmallorca.dto.Servei;

/**
 *
 * @author Miguel
 */
public class PanelInsertAllotjament extends javax.swing.JPanel {

    private Allotjament allotjament = null;
    private DataAccess da = new DataAccess();
    private Main mainJFrame = null;

    /**
     * Creates new form PanelDetallAllotjament
     */
    public PanelInsertAllotjament(Main mainJPanel) {
        initComponents();
        this.mainJFrame = mainJPanel;
        setSize(780, 490);

        inicialitzaFields();
    }

    private void inicialitzaFields() {
//        txtNom.setText(allotjament.getNom());
//        txtAdresa.setText(allotjament.getAdresa());
//        txaDescripcio.setText(allotjament.getDescripcio());
        initCmbMunicipis();
//        spnNumPersones.setValue(allotjament.getNum_persones());
//        txtPreuNit.setText(Float.toString(allotjament.getPreu_per_nit()));
//        initServeis();
    }

    private void initCmbMunicipis() {
        var municipis = da.getMunicipis();
        DefaultComboBoxModel<String> cbm = new DefaultComboBoxModel<>();
        for (Municipi m : municipis) {
            cbm.addElement(m.getNom());
        }
        cmbMunicipi.setModel(cbm);
//        cmbMunicipi.setSelectedItem(allotjament.getMunicipi());
    }

    private void initServeis() {
//        var serveis = da.getServeisAllotjament(allotjament.getId());
//        for (Servei s : serveis) {
//            switch(s.getDescripcio()) {
//                case "Piscina": chkPiscina.setSelected(true);
//                break;
//                case "Aire acondicionat": chkAireAcondicionat.setSelected(true);
//                break;
//                case "Wifi": chkWifi.setSelected(true);
//                break;
//                case "Aparcament": chkAparcament.setSelected(true);
//                break;
//                case "Admet mascotes": chkMascotes.setSelected(true);
//                break;
//                case "Ascensor": chkAscensor.setSelected(true);
//                break;
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabelnom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtAdressa = new javax.swing.JTextField();
        jLabelAdressa = new javax.swing.JLabel();
        txtDescripcio = new javax.swing.JTextField();
        jLabelDescripcio = new javax.swing.JLabel();
        jLabelMunicipi = new javax.swing.JLabel();
        txtValoracio = new javax.swing.JTextField();
        jLabelValoracio = new javax.swing.JLabel();
        jLabelPreu = new javax.swing.JLabel();
        jLabelNumPers = new javax.swing.JLabel();
        spnNumPersones = new javax.swing.JSpinner();
        spnPreu = new javax.swing.JSpinner();
        cmbMunicipi = new javax.swing.JComboBox<>();
        pnlServeis = new javax.swing.JPanel();
        chkPiscina = new javax.swing.JCheckBox();
        chkMascotes = new javax.swing.JCheckBox();
        chkAscensor = new javax.swing.JCheckBox();
        chkAireAcondicionat = new javax.swing.JCheckBox();
        chkAparcament = new javax.swing.JCheckBox();
        chkWifi = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setForeground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(480, 500));
        setLayout(null);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-24 (1).png"))); // NOI18N
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(20, 20, 65, 31);

        jLabelnom.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnom.setText("Nom:");
        add(jLabelnom);
        jLabelnom.setBounds(30, 90, 100, 16);

        txtNom.setForeground(new java.awt.Color(255, 255, 255));
        add(txtNom);
        txtNom.setBounds(30, 110, 137, 22);

        txtAdressa.setForeground(new java.awt.Color(255, 255, 255));
        add(txtAdressa);
        txtAdressa.setBounds(30, 160, 137, 22);

        jLabelAdressa.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAdressa.setText("Adressa:");
        add(jLabelAdressa);
        jLabelAdressa.setBounds(30, 140, 140, 16);

        txtDescripcio.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(txtDescripcio);
        txtDescripcio.setBounds(30, 280, 420, 110);

        jLabelDescripcio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcio.setText("Descripcio: ");
        add(jLabelDescripcio);
        jLabelDescripcio.setBounds(30, 260, 100, 16);

        jLabelMunicipi.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMunicipi.setText("Municipi: ");
        add(jLabelMunicipi);
        jLabelMunicipi.setBounds(30, 200, 120, 16);

        txtValoracio.setForeground(new java.awt.Color(255, 255, 255));
        add(txtValoracio);
        txtValoracio.setBounds(180, 110, 76, 22);

        jLabelValoracio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValoracio.setText("Valoració:");
        add(jLabelValoracio);
        jLabelValoracio.setBounds(182, 90, 70, 16);

        jLabelPreu.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPreu.setText("Preu:");
        add(jLabelPreu);
        jLabelPreu.setBounds(280, 90, 60, 16);

        jLabelNumPers.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumPers.setText("Nº de Personas:");
        add(jLabelNumPers);
        jLabelNumPers.setBounds(360, 90, 90, 16);
        add(spnNumPersones);
        spnNumPersones.setBounds(360, 110, 84, 22);
        add(spnPreu);
        spnPreu.setBounds(280, 110, 64, 22);

        cmbMunicipi.setForeground(new java.awt.Color(255, 255, 255));
        cmbMunicipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alaró", "Inca" }));
        add(cmbMunicipi);
        cmbMunicipi.setBounds(30, 220, 137, 22);

        pnlServeis.setBorder(javax.swing.BorderFactory.createTitledBorder("Serveis"));
        pnlServeis.setForeground(new java.awt.Color(255, 255, 255));

        chkPiscina.setForeground(new java.awt.Color(255, 255, 255));
        chkPiscina.setText("Piscina");

        chkMascotes.setForeground(new java.awt.Color(255, 255, 255));
        chkMascotes.setText("Mascotes");
        chkMascotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMascotesActionPerformed(evt);
            }
        });

        chkAscensor.setForeground(new java.awt.Color(255, 255, 255));
        chkAscensor.setText("Ascensor");

        chkAireAcondicionat.setForeground(new java.awt.Color(255, 255, 255));
        chkAireAcondicionat.setText("Aire Acondicionat");

        chkAparcament.setForeground(new java.awt.Color(255, 255, 255));
        chkAparcament.setText("Aparcament");

        chkWifi.setForeground(new java.awt.Color(255, 255, 255));
        chkWifi.setText("Wifi");

        javax.swing.GroupLayout pnlServeisLayout = new javax.swing.GroupLayout(pnlServeis);
        pnlServeis.setLayout(pnlServeisLayout);
        pnlServeisLayout.setHorizontalGroup(
            pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServeisLayout.createSequentialGroup()
                .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServeisLayout.createSequentialGroup()
                        .addComponent(chkPiscina)
                        .addGap(32, 32, 32)
                        .addComponent(chkAireAcondicionat))
                    .addGroup(pnlServeisLayout.createSequentialGroup()
                        .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAscensor)
                            .addComponent(chkMascotes))
                        .addGap(18, 18, 18)
                        .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAparcament)
                            .addComponent(chkWifi))))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        pnlServeisLayout.setVerticalGroup(
            pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServeisLayout.createSequentialGroup()
                .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPiscina)
                    .addComponent(chkAireAcondicionat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAparcament)
                    .addComponent(chkMascotes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkWifi)
                    .addComponent(chkAscensor))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        add(pnlServeis);
        pnlServeis.setBounds(180, 140, 270, 110);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-verified-scroll-48 (1).png"))); // NOI18N
        jLabel1.setText(" Nou Allotjament");
        add(jLabel1);
        jLabel1.setBounds(130, 10, 220, 48);

        btnInsert.setFont(btnInsert.getFont().deriveFont(btnInsert.getFont().getStyle() | java.awt.Font.BOLD));
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.setLabel("Insertar");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        add(btnInsert);
        btnInsert.setBounds(360, 410, 90, 40);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1);
        jSeparator1.setBounds(0, 64, 780, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainJFrame.showPnlLlistaAllotjaments();
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void chkMascotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMascotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMascotesActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        allotjament = new Allotjament();
        allotjament.setNom(txtNom.getText());
        allotjament.setAdresa(txtAdressa.getText());
        allotjament.setMunicipi(cmbMunicipi.getSelectedItem().toString());
        allotjament.setId_municipi(cmbMunicipi.getSelectedIndex() + 1);
        allotjament.setDescripcio(txtDescripcio.getText());
        try {
            spnNumPersones.commitEdit();
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }
        allotjament.setNum_persones((Integer) spnNumPersones.getValue());
        allotjament.setId_propietari(mainJFrame.getAuthenticatedUser().getId());
        float preuPerNit = Float.parseFloat(spnPreu.getValue().toString());
        allotjament.setPreu_per_nit(preuPerNit);
        int idNouAllotjament = da.insertAllotjament(allotjament);

        if (idNouAllotjament <= 0) {
            JOptionPane.showMessageDialog(mainJFrame, "Error insertant nou allotjament.");
            return;
        }

        if (chkPiscina.isSelected()) {
            da.insertServei(1, idNouAllotjament);
        }
        if (chkMascotes.isSelected()) {
            da.insertServei(2, idNouAllotjament);
        }
        if (chkAireAcondicionat.isSelected()) {
            da.insertServei(3, idNouAllotjament);
        }
        if (chkAscensor.isSelected()) {
            da.insertServei(4, idNouAllotjament);
        }
        if (chkAparcament.isSelected()) {
            da.insertServei(5, idNouAllotjament);
        }
        if (chkWifi.isSelected()) {
            da.insertServei(6, idNouAllotjament);
        }

        JOptionPane.showMessageDialog(mainJFrame, "Allotjament insertat correctament.");

        mainJFrame.reloadPnlLlistaAllotjaments();

    }//GEN-LAST:event_btnInsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInsert;
    private javax.swing.JCheckBox chkAireAcondicionat;
    private javax.swing.JCheckBox chkAparcament;
    private javax.swing.JCheckBox chkAscensor;
    private javax.swing.JCheckBox chkMascotes;
    private javax.swing.JCheckBox chkPiscina;
    private javax.swing.JCheckBox chkWifi;
    private javax.swing.JComboBox<String> cmbMunicipi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAdressa;
    private javax.swing.JLabel jLabelDescripcio;
    private javax.swing.JLabel jLabelMunicipi;
    private javax.swing.JLabel jLabelNumPers;
    private javax.swing.JLabel jLabelPreu;
    private javax.swing.JLabel jLabelValoracio;
    private javax.swing.JLabel jLabelnom;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlServeis;
    private javax.swing.JSpinner spnNumPersones;
    private javax.swing.JSpinner spnPreu;
    private javax.swing.JTextField txtAdressa;
    private javax.swing.JTextField txtDescripcio;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtValoracio;
    // End of variables declaration//GEN-END:variables
}
