package spdvid.evtmallorca.panels;

import spdvid.evtmallorca.Main;
import spdvid.evtmallorca.dataaccess.DataAccess;
import spdvid.evtmallorca.dto.Allotjament;
import spdvid.evtmallorca.tablemodels.AllotjamentTableModel;

/**
 *
 * @author Miguel
 */
public class PanelLlistaAllojtaments extends javax.swing.JPanel {
    private DataAccess da = new DataAccess();
    private Main mainJFrame = null;
    
    /**
     * Creates new form pnlAllojtaments
     */
    public PanelLlistaAllojtaments(int userId, Main mainJFrame) {
        initComponents();
        this.mainJFrame = mainJFrame;
        setSize(780, 490);
        tblAllotjaments.setModel(new AllotjamentTableModel((da.getAllotjaments(userId)))); 
        int total = tblAllotjaments.getRowCount();
        lblNumEstabliments.setText("S'han trobat " + total + " establiments.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblAllotjaments = new javax.swing.JTable();
        btnShowInsertPanel = new javax.swing.JButton();
        lblNumEstabliments = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(780, 490));

        tblAllotjaments.setForeground(new java.awt.Color(255, 255, 255));
        tblAllotjaments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAllotjaments.setMaximumSize(new java.awt.Dimension(300, 80));
        tblAllotjaments.setName(""); // NOI18N
        tblAllotjaments.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblAllotjaments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllotjamentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAllotjaments);

        btnShowInsertPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnShowInsertPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-más-24.png"))); // NOI18N
        btnShowInsertPanel.setText("Nou");
        btnShowInsertPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShowInsertPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInsertPanelActionPerformed(evt);
            }
        });

        lblNumEstabliments.setForeground(new java.awt.Color(255, 255, 255));
        lblNumEstabliments.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumEstabliments.setText("S'han trobat x establiments.");

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-dormitorio-48.png"))); // NOI18N
        jLabel1.setText("Els Teus Allotjaments");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNumEstabliments, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnShowInsertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblNumEstabliments))
                    .addComponent(btnShowInsertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblAllotjamentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllotjamentsMouseClicked
        AllotjamentTableModel atbm = (AllotjamentTableModel) tblAllotjaments.getModel();
        int selectedRowIndex = tblAllotjaments.getSelectedRow();
        //atbm.getValueAt(selectedRowIndex, 0);
        Allotjament selectedAllotjament = atbm.getValueAtRow(selectedRowIndex);
        System.out.print("selected allotjament id: " + selectedAllotjament.getId());
        //System.out.print(((Main)this.getRootPane().getContentPane()));
//        ((Main)this.getRootPane().getContentPane()).showPnlDetallAllotjament(selectedAllotjament);
        mainJFrame.showPnlDetallAllotjament(selectedAllotjament);
    }//GEN-LAST:event_tblAllotjamentsMouseClicked

    private void btnShowInsertPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInsertPanelActionPerformed
        mainJFrame.showPnlInsertAllotjament();
    }//GEN-LAST:event_btnShowInsertPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowInsertPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNumEstabliments;
    private javax.swing.JTable tblAllotjaments;
    // End of variables declaration//GEN-END:variables
}
