package spdvid.evtmallorca.panels;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.awt.Font;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import spdvid.evtmallorca.Main;
import spdvid.evtmallorca.dataaccess.DataAccess;
import spdvid.evtmallorca.dto.Allotjament;
import spdvid.evtmallorca.dto.Comentari;
import spdvid.evtmallorca.dto.Municipi;
import spdvid.evtmallorca.dto.Servei;

/**
 *
 * @author Miguel
 */
public class PanelDetallAllotjament extends javax.swing.JPanel {

    private Allotjament allotjament = null;
    private DataAccess da = new DataAccess();
    private Main mainJFrame = null;

    /**
     * Creates new form PanelDetallAllotjament
     */
    public PanelDetallAllotjament(Allotjament allotjament, Main mainJPanel) {
        initComponents();
           
        this.allotjament = allotjament;
        this.mainJFrame = mainJPanel;
        setSize(780, 700);

        inicialitzaFields();
    }

    private void inicialitzaFields() {
        txtNom.setText(allotjament.getNom());
        txtAdressa.setText(allotjament.getAdresa());
        txtDescripcio.setText(allotjament.getDescripcio());
        initCmbMunicipis();
        spnNumPersones.setValue(allotjament.getNum_persones());
        spnPreu.setValue(allotjament.getNum_persones());
        initServeis();
        initComentaris();
        txtValoracio.setText(Float.toString(da.getValoracioAllotjamentAvg(allotjament.getId())));
    }

    private void initCmbMunicipis() {
        var municipis = da.getMunicipis();
        DefaultComboBoxModel<String> cbm = new DefaultComboBoxModel<>();
        for (Municipi m : municipis) {
            cbm.addElement(m.getNom());
        }
        cmbMunicipi.setModel(cbm);
        cmbMunicipi.setSelectedItem(allotjament.getMunicipi());
    }

    private void initServeis() {
        var serveis = da.getServeisAllotjament(allotjament.getId());
        for (Servei s : serveis) {
            switch (s.getDescripcio()) {
                case "Piscina":
                    chkPiscina.setSelected(true);
                    break;
                case "Aire condicionat":
                    chkAireAcondicionat.setSelected(true);
                    break;
                case "Wifi":
                    chkWifi.setSelected(true);
                    break;
                case "Aparcament":
                    chkAparcament.setSelected(true);
                    break;
                case "Admet mascotes":
                    chkMascotes.setSelected(true);
                    break;
                case "Ascensor":
                    chkAscensor.setSelected(true);
                    break;
            }
        }
    }

    private void initComentaris() {
        var comentaris = da.getComentaris(allotjament.getId());
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        for (Comentari comentari : comentaris) {
            LocalDateTime dataihora = LocalDateTime.parse(comentari.getDataihora(), dtf);
            txaComentaris.append(comentari.getIdUsuari()
                    + " said:\n " + comentari.getText() + "\nOn "
                    + dataihora.toString() + "\n\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnPrevImage = new javax.swing.JButton();
        btnNextImage = new javax.swing.JButton();
        chkAutoMan = new javax.swing.JCheckBox();
        lblImageFileName = new javax.swing.JLabel();
        jLabelnom = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtAdressa = new javax.swing.JTextField();
        jLabelAdressa = new javax.swing.JLabel();
        txtDescripcio = new javax.swing.JTextField();
        jLabelDescripcio = new javax.swing.JLabel();
        jLabelMunicipi = new javax.swing.JLabel();
        txtValoracio = new javax.swing.JTextField();
        jLabelValoracio = new javax.swing.JLabel();
        jLabelPreu = new javax.swing.JLabel();
        jLabelComentaris = new javax.swing.JLabel();
        jButtonActualitzar = new javax.swing.JButton();
        jLabelNumPers = new javax.swing.JLabel();
        spnNumPersones = new javax.swing.JSpinner();
        spnPreu = new javax.swing.JSpinner();
        cmbMunicipi = new javax.swing.JComboBox<>();
        pnlServeis = new javax.swing.JPanel();
        chkPiscina = new javax.swing.JCheckBox();
        chkMascotes = new javax.swing.JCheckBox();
        chkAscensor = new javax.swing.JCheckBox();
        chkAireAcondicionat = new javax.swing.JCheckBox();
        chkAparcament = new javax.swing.JCheckBox();
        chkWifi = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaComentaris = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(780, 700));
        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Imatges"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(30, 380, 710, 160);

        btnBack.setText(" < Atras");
        btnBack.setMaximumSize(new java.awt.Dimension(86, 23));
        btnBack.setMinimumSize(new java.awt.Dimension(86, 23));
        btnBack.setPreferredSize(new java.awt.Dimension(86, 23));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(30, 20, 90, 30);

        btnPrevImage.setText("<");
        add(btnPrevImage);
        btnPrevImage.setBounds(620, 570, 40, 23);

        btnNextImage.setText(">");
        add(btnNextImage);
        btnNextImage.setBounds(690, 570, 40, 23);

        chkAutoMan.setText("Auto");
        add(chkAutoMan);
        chkAutoMan.setBounds(40, 560, 85, 20);

        lblImageFileName.setText("Nom del fitxer de imatge i tamany en KB");
        lblImageFileName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblImageFileName);
        lblImageFileName.setBounds(110, 570, 260, 30);

        jLabelnom.setText("Nom:");
        add(jLabelnom);
        jLabelnom.setBounds(29, 80, 30, 16);

        txtNom.setText("jTextField1");
        add(txtNom);
        txtNom.setBounds(29, 102, 137, 22);

        txtAdressa.setText("jTextField1");
        add(txtAdressa);
        txtAdressa.setBounds(29, 162, 137, 22);

        jLabelAdressa.setText("Adressa:");
        add(jLabelAdressa);
        jLabelAdressa.setBounds(29, 140, 44, 16);

        txtDescripcio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDescripcio.setText("jTextField1");
        add(txtDescripcio);
        txtDescripcio.setBounds(29, 280, 410, 82);

        jLabelDescripcio.setText("Descripcio: ");
        add(jLabelDescripcio);
        jLabelDescripcio.setBounds(29, 258, 61, 16);

        jLabelMunicipi.setText("Municipi: ");
        add(jLabelMunicipi);
        jLabelMunicipi.setBounds(29, 196, 53, 16);

        txtValoracio.setText("jTextField1");
        add(txtValoracio);
        txtValoracio.setBounds(187, 102, 71, 22);

        jLabelValoracio.setText("Valoració:");
        add(jLabelValoracio);
        jLabelValoracio.setBounds(187, 80, 52, 16);

        jLabelPreu.setText("Preu:");
        add(jLabelPreu);
        jLabelPreu.setBounds(276, 80, 27, 16);

        jLabelComentaris.setText("Comentaris:");
        add(jLabelComentaris);
        jLabelComentaris.setBounds(470, 80, 64, 16);

        jButtonActualitzar.setText("Actualitzar");
        jButtonActualitzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualitzarActionPerformed(evt);
            }
        });
        add(jButtonActualitzar);
        jButtonActualitzar.setBounds(600, 20, 137, 33);

        jLabelNumPers.setText("Nº de Personas:");
        add(jLabelNumPers);
        jLabelNumPers.setBounds(359, 80, 83, 16);
        add(spnNumPersones);
        spnNumPersones.setBounds(358, 102, 84, 22);
        add(spnPreu);
        spnPreu.setBounds(276, 102, 64, 22);

        cmbMunicipi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alaró", "Inca" }));
        add(cmbMunicipi);
        cmbMunicipi.setBounds(29, 224, 137, 22);

        pnlServeis.setBorder(javax.swing.BorderFactory.createTitledBorder("Serveis"));
        pnlServeis.setLayout(null);

        chkPiscina.setText("Piscina");
        pnlServeis.add(chkPiscina);
        chkPiscina.setBounds(5, 18, 60, 20);

        chkMascotes.setText("Mascotes");
        chkMascotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMascotesActionPerformed(evt);
            }
        });
        pnlServeis.add(chkMascotes);
        chkMascotes.setBounds(5, 44, 73, 20);

        chkAscensor.setText("Ascensor");
        pnlServeis.add(chkAscensor);
        chkAscensor.setBounds(5, 70, 71, 20);

        chkAireAcondicionat.setText("Aire Acondicionat");
        pnlServeis.add(chkAireAcondicionat);
        chkAireAcondicionat.setBounds(97, 18, 118, 20);

        chkAparcament.setText("Aparcament");
        pnlServeis.add(chkAparcament);
        chkAparcament.setBounds(96, 44, 88, 20);

        chkWifi.setText("Wifi");
        pnlServeis.add(chkWifi);
        chkWifi.setBounds(96, 70, 44, 20);

        add(pnlServeis);
        pnlServeis.setBounds(184, 140, 258, 110);

        txaComentaris.setColumns(20);
        txaComentaris.setRows(5);
        jScrollPane2.setViewportView(txaComentaris);

        add(jScrollPane2);
        jScrollPane2.setBounds(470, 110, 270, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainJFrame.showPnlLlistaAllotjaments();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButtonActualitzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualitzarActionPerformed
        // TODO add your handling code here:
        allotjament.setNom(txtNom.getText());
        allotjament.setAdresa(txtAdressa.getText());
        allotjament.setMunicipi(cmbMunicipi.getSelectedItem().toString());
        allotjament.setId_municipi(cmbMunicipi.getSelectedIndex() + 1);  // ERROR!!!
        allotjament.setDescripcio(txtDescripcio.getText());
        try {
            spnNumPersones.commitEdit();
        } catch (java.text.ParseException e) {
            e.printStackTrace();
        }
        allotjament.setNum_persones((Integer) spnNumPersones.getValue());
        float preuPerNit = Float.parseFloat(spnPreu.getValue().toString());
        allotjament.setPreu_per_nit(preuPerNit);

        da.updateAllojtament(allotjament);

        int[] serveis = new int[6];
        if (chkPiscina.isSelected()) {
            serveis[0] = 1;
        }
        if (chkMascotes.isSelected()) {
            serveis[1] = 1;
        }
        if (chkAireAcondicionat.isSelected()) {
            serveis[2] = 1;
        }
        if (chkAscensor.isSelected()) {
            serveis[3] = 1;
        }
        if (chkAparcament.isSelected()) {
            serveis[4] = 1;
        }
        if (chkWifi.isSelected()) {
            serveis[5] = 1;
        }
        da.updateServeisAllotjament(allotjament.getId(), serveis);

        JOptionPane.showMessageDialog(mainJFrame, "Allotjament updated correctly.");
        mainJFrame.showPnlLlistaAllotjaments();

    }//GEN-LAST:event_jButtonActualitzarActionPerformed

    private void chkMascotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMascotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMascotesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNextImage;
    private javax.swing.JButton btnPrevImage;
    private javax.swing.JCheckBox chkAireAcondicionat;
    private javax.swing.JCheckBox chkAparcament;
    private javax.swing.JCheckBox chkAscensor;
    private javax.swing.JCheckBox chkAutoMan;
    private javax.swing.JCheckBox chkMascotes;
    private javax.swing.JCheckBox chkPiscina;
    private javax.swing.JCheckBox chkWifi;
    private javax.swing.JComboBox<String> cmbMunicipi;
    private javax.swing.JButton jButtonActualitzar;
    private javax.swing.JLabel jLabelAdressa;
    private javax.swing.JLabel jLabelComentaris;
    private javax.swing.JLabel jLabelDescripcio;
    private javax.swing.JLabel jLabelMunicipi;
    private javax.swing.JLabel jLabelNumPers;
    private javax.swing.JLabel jLabelPreu;
    private javax.swing.JLabel jLabelValoracio;
    private javax.swing.JLabel jLabelnom;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImageFileName;
    private javax.swing.JPanel pnlServeis;
    private javax.swing.JSpinner spnNumPersones;
    private javax.swing.JSpinner spnPreu;
    private javax.swing.JTextArea txaComentaris;
    private javax.swing.JTextField txtAdressa;
    private javax.swing.JTextField txtDescripcio;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtValoracio;
    // End of variables declaration//GEN-END:variables

}
